package cz.ethereal.gokasaprinter

const val GOKASA_PRINTER_SHARED_PREFERENCES = "GOKASA_PRINTER_SHARED_PREFERENCES"
const val GOKASA_PRINTER_DEBUG = "GOKASA_PRINTER_DEBUG"
const val SAVED_BLUETOOTH_DEVICE = "SAVED_BLUETOOTH_DEVICE"
const val SAVED_BLUETOOTH_PERMISSION_GRANTED = "SAVED_BLUETOOTH_PERMISSION_GRANTED"
const val SAVED_APP_LANGUAGE = "SAVED_APP_LANGUAGE"
